### ISSUE TITLE
Некорректная работа поиска в заказах  client worker

### ISSUE THREAD

**Issue by Butya8** [nambaprofi/nambaprofi-pub#19]
При вводе части ключевого слова/полного слова -  выводит все заказы содержащие данное слово
Шаги воспроизведения 
1. Зайти в раздел "Заказы"
2. В поле поиска написать слово "лампочку", и поискать. 
Ожидаемый результат 
Отображение заказа с данным словом "Повесить лампочку"
Фактический результат 
Нет результатов

**Comment by Butya8** [comment]
android

**Comment by nambaprofi** [comment]
#12

**Comment by nambaprofi** [comment]
Duplicate of #12
