### ISSUE TITLE
 раздел заказы-client worker

### ISSUE THREAD

**Issue by Butya8** [nambaprofi/nambaprofi-pub#22]
Поисковик в приложении не работает в разделе «заказы». 
Существует заказ : "нужен визажист для мэйк апа". 
в поисковик вводим "визажист", но заказ не отображается

**Comment by nambaprofi** [comment]
![orders-filter-x9784](https://user-images.githubusercontent.com/86819754/191486250-3110d047-9b0d-4c47-9ef0-5ef12b2c5c0c.jpg)

**Comment by Butya8** [comment]
проблема в регистрозависимости. Попробуйте ввести Визажист, поиск не найдет, но если ввести визажист, то найдет. Надо предусмотреть логику, когда будет работать поиск при любом вводе слова вне зависимости от верхнего регистра или нижнего регистра.

**Comment by Butya8** [comment]
@nambaprofi

**Comment by nambaprofi** [comment]
Duplicate of #12
