### ISSUE TITLE
Некликабельные разделы на главной странице Client - worker

### ISSUE THREAD

**Issue by Butya8** [nambaprofi/nambaprofi-pub#24]
На главной странице горячие клавиши не направляют в свой раздел
Шаги воспроизведения

Зайти на главную страницу приложения.
Нажать на горячие клавиши: ОТКЛИКИ , МОИ ЗАКАЗЫ, РЕЙТИНГ
Ожидаемый результат
Открытие раздела
Фактический результат
Отображение информации: не переходит в раздел

**Comment by nambaprofi** [comment]
Duplicate of #16
