### ISSUE TITLE
Некорректная работа прикрепления файла в заказе  Web-view

### ISSUE THREAD

**Issue by BubuSarah** [nambaprofi/nambaprofi-pub#26]
При создании заказа, в прикреплении файла нет возможности загрузить файл(фото или документ) с устройства. 
Web-view
1. Нажать на + Заказать 
2. Добавить данные в описание, даты, адрес и категории
3.  Нажать на прикрепить файл. 

Ожидаемый результат: 
1. Возможность загрузить файл или документ
2.  Сфотографировать   

Фактический результат: Только моментальное фото, отсутствует возможность загрузки

**Comment by nambaprofi** [comment]
в приложении исполнителя фото файлы можно выбрать?

**Comment by nambaprofi** [comment]
Duplicate of #34

**Comment by BubuSarah** [comment]
баг не исправлен
