### ISSUE TITLE
Отсутствие кнопки "Стать исполнителем" Web-view

### ISSUE THREAD

**Issue by BubuSarah** [nambaprofi/nambaprofi-pub#27]
Описание: Ссылка на регистрацию для того, чтобы стать исполнителем ведущая на страницу регистрации

Местоположение данной кнопки: 

Web-view на главной странице после раздела Категории услуг. В макете есть данная кнопка.

**Comment by BubuSarah** [comment]
![image](https://user-images.githubusercontent.com/113238922/203241125-f4ba6f57-1945-4679-8904-75634659abb6.png)

**Comment by BubuSarah** [comment]
Данный баг исправлен не до конца. Здесь только категории добавили, а доверенные лица, согласие на обработку данных (4 галочки), номер телефона (куда поступают логин и пароль) не добавлены поля. Просьба дать обратную связь.

**Comment by nambaprofi** [comment]
В макете это есть?

**Comment by BubuSarah** [comment]
Доверенные лица, согласие на обработку данных (4 галочки) есть в макете. 

А насчет номера телефона, это по логике функционала которую Вы добавили. После категорий - выходит уведомление, что логин и одноразовый пароль придут к Вам на номер телефона. Проверили, логин и пароль не поступают.

**Comment by nambaprofi** [comment]
Проверяйте с макетом который был в разработке. Логин и пароль не поступают по причине отсутствия сервиса смс который зависит от сервиса nambaone (не было функциональности и\или документации)
