### ISSUE TITLE
Некорректная работа кнопки "Назад" для выхода на главную страницу Web-view

### ISSUE THREAD

**Issue by BubuSarah** [nambaprofi/nambaprofi-pub#30]
**Описание** 
Кнопка "Назад" должна перебрасывать на главную страницу. 
**Шаги воспроизведения** 
Web-view
1. Зайти в раздел ""Еще""/""Уведомления""/""Заказы""
2. Нажать на кнопку 'Назад"" 
**Ожидаемый результат** 
Отображение главной страницы 
**Фактический результат**
Отсутствие возможности перехода на главную страницу. Кнопка назад некликабельная

**Comment by nambaprofi** [comment]
кнопка "назад" имеет ссылку native://goBack аналогичную предыдущей версии webview по требованию приложения N1

<img height=400 src="https://user-images.githubusercontent.com/86819754/205285188-3e228fdf-f404-40c9-a53a-893f2697f76d.gif"/>

**Comment by BubuSarah** [comment]
Внутри web-view не работает кнопка назад, протестируйте. В шагах воспроизведения описано все.

**Comment by nambaprofi** [comment]
На скрине выше видно, кнопка работает. Из разделов "уведомления", "заказы", "еще" - выход в приложение N1

**Comment by BubuSarah** [comment]
https://user-images.githubusercontent.com/113238922/205594072-fcde1d29-2ca9-40a4-b78d-189feedf4ab7.mp4

проверьте кнопку назад внутри приложения, на первую страницу, которая на видео невозможно попасть, нужно заново выходить и вход делать.

**Comment by BubuSarah** [comment]
обратите внимание на оранжевую стрелку назад.

**Comment by nambaprofi** [comment]
Эта кнопка предназначена для выхода, когда оно работает внутри приложения N1, а не в браузере как у вас.  
То что вы описали это #25

**Comment by BubuSarah** [comment]
а как Вы предлагаете выйти на главную страницу которая первая отображена на видео?

**Comment by nambaprofi** [comment]
Вопрос не по адресу. Спросите у того, кто рисовал макет.  Самое очевидное добавить кнопку главная, как у приложения исполнителя.
