### ISSUE TITLE
Некорректная работа фильтра "Выполненные" Web-view и исполнительская часть

### ISSUE THREAD

**Issue by BubuSarah** [nambaprofi/nambaprofi-pub#31]
**Описание** 
Для быстрого поиска среди заданий, применяются фильтры.
**Шаги воспроизведения**
Web-view и исполнительская часть
1. Зайти в раздел ""Заказы""
2. Нажать на фильтр
3. Выбрать ""Выполненные"
**Ожидаемый результат**
Отображение списка выполненных заданий . 
ID заказа - d799be7c-c0cb-48d2-aec3-c7f74c480c3f  "Повесить лампочку" - заказчик Иван Андреев

**Фактический результат**
Отсутствие списка выполненных заказа.

**Comment by nambaprofi** [comment]
![435345](https://user-images.githubusercontent.com/86819754/205278831-66be5912-1254-4aec-993a-79f545d3160a.JPG)
 у этого заказа статус "закрыт"

**Comment by nambaprofi** [comment]
Не подтверждается. фильтр работает корректно. Статус "**выполнен**" назначается **после завершения** заказа **исполнителем**
