### ISSUE TITLE
Некорректная работа прикрепления файла в Профиле клиента Web-view

### ISSUE THREAD

**Issue by BubuSarah** [nambaprofi/nambaprofi-pub#34]
**Описание** 
При редактировании, в прикреплении аватара нет возможности загрузить файл(фото или документ) с устройства. 
**Шаги воспроизведения**
Web-view
1. Зайти в раздел Еще  
2. Редактировать профиль 
3.  Нажать на прикрепить файл. 
**Ожидаемый результат**
"1. Возможность загрузить файл или документ
  2.  Сфотографировать   
**Фактический результат**
Только моментальное фото, отсутствует возможность загрузки

**Comment by nambaprofi** [comment]
какое поведение у этого поля в андроид сборке приложения исполнителя?

**Comment by BubuSarah** [comment]
там наоборот, в APK можно только прикреплять документ, фото сделать невозможно.

**Comment by nambaprofi** [comment]
эта проблема относится к приложению N1

**Comment by nambaprofi** [comment]
эта проблема относится к приложению N1

**Comment by BubuSarah** [comment]
Данный функционал не добавлен вообще. Баг не исправлен

**Comment by nambaprofi** [comment]
Не планируется. написано выше причину.
