### ISSUE TITLE
Блок FAQ. Админ панель

### ISSUE THREAD

**Issue by BubuSarah** [nambaprofi/nambaprofi-pub#42]
***Описание*** 
Данный раздел позволяет вносить актуальные данные по часто задаваемым вопросам. Редактировать, добавлять и удалять 
***Шаги воспроизведения*** 
"1. Зайти в админку
2. В разделе Контент - FAQ актуализировать данные "
***Ожидаемый результат***
Редактировать, добавлять и удалять информацию по актуальным вопросам 
***Фактический результат***
Пустая страница

**Comment by BubuSarah** [comment]
@nambaprofi

**Comment by nambaprofi** [comment]
почистите кэш.

**Comment by BubuSarah** [comment]
![image](https://user-images.githubusercontent.com/113238922/204219280-8debba85-300b-4c28-85a3-37d4c21bb659.png)
не дает написать тему вопроса. Непонятная ошибка. Просьба проверить.
