### ISSUE TITLE
Некорректная работа фильтра в админ панель. 

### ISSUE THREAD

**Issue by BubuSarah** [nambaprofi/nambaprofi-pub#44]
**Описание** 
В разделах Заказы, Предложения 
Не работает фильтр. 
**Шаги воспроизведения:**
1. Зайти в админку
2. Зайти в раздела Заказы, Предложения
3. Настроить фильтры по статусу в Заказах - Оpen
4. Настроить фильтр по цене в Предложениях - 10 000
**Ожидаемый результат**
Фильтрация данных по применным фильтрам
Фактический результат
Фильтры не применяются, данные отображаются как и в начальном виде.

**Comment by nambaprofi** [comment]
заказы->фильтр->статус не подтверждается.
![3455gf](https://user-images.githubusercontent.com/86819754/204243387-87470d37-2734-4746-bbde-18d1627696e2.JPG)

**Comment by BubuSarah** [comment]
1. По статусам заработал. Благодарю.
2. По ценам фильтр не работает
3. По ключевым словам столбец Комментарий не работает. 
4. По дате фильтр не работает 
5. По имени заказчика тоже фильтр не работает.

**Comment by BubuSarah** [comment]
Почему закрываете баг, хотя он не исправлен? 

По ценам фильтр не работает
По ключевым словам столбец Комментарий не работает.
По дате фильтр не работает
По имени заказчика тоже фильтр не работает.

**Comment by nambaprofi** [comment]
Исправлен и закрыт. Это не значит, что Вы увидите эти изменения моментально у себя на сервере. Только после загрузки обновлений.

**Comment by BubuSarah** [comment]
А как и когда я смогу проверить? Дайте развернутую информацию.

**Comment by nambaprofi** [comment]
вам сообщат
