### ISSUE TITLE
Нет возможности выхода из аккаунта. Client and worker

### ISSUE THREAD

**Issue by BubuSarah** [nambaprofi/nambaprofi-pub#45]
**Описание**
В разделе профиль, должна быть кнопка Выйти, чтобы можно было переключиться между аккаунтами. 
**Шаги воспроизведения**
1. В приложении для исполнителей, Зайти в раздел Профиль
2. Нажать на кнопку Выход
**Ожидаемый результат**
"Выход из аккаунта
Возможность сменить аккаунт "
**Фактический результат**
Нет данного функционала

**Comment by nambaprofi** [comment]
Выход из аккаунта в приложении исполнителя.
